# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerVideoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_video_filervideopluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('width', models.PositiveIntegerField(blank=True, help_text='The width of the video, in CSS pixels', null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, help_text='The height of the video, in CSS pixels', null=True, verbose_name='height')),
                ('autoplay', models.BooleanField(default=False, help_text='Automatically begin playback of the video as soon as it can do so without stopping', verbose_name='play automatically')),
                ('controls', models.BooleanField(default=False, help_text='Expose a user interface for controlling playback of the video', verbose_name='show controls')),
                ('loop', models.BooleanField(default=False, help_text='Seek back to the start of the video upon reaching the end', verbose_name='loop')),
                ('muted', models.BooleanField(default=False, help_text='Mute the video soundtrack', verbose_name='muted')),
                ('poster', filer.fields.image.FilerImageField(blank=True, help_text='An image to show while no video data is available', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filer.Image', verbose_name='poster image')),
                ('video_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filer.File', verbose_name='Video file')),
            ],
            options={
                'verbose_name': 'Self hosted video',
                'verbose_name_plural': 'Self hosted videos',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
